### ISSUE TITLE
Large snapshots should be treated specially

### ISSUE THREAD

**Issue by MikailBag** [mitsuhiko/insta#129]
Currently, when test fails and snapshot is large, insta will still display beautiful precise diff between old and new snapshot.
However diff generation requires O(N**2) memory, so it can easily lead to OOM.

I think, `insta` should not generate accurate diff for large snapshots (ones where `old_line_count * new_line_count` > THRESHOLD).

I'm not sure if this problem should be solved in `insta` or `difference`. Either way, I'm ready to send a PR.

Workaround:
1) Make note of snapshot path.
2) Open snapshot in editor and clear it.
3) Done, no OOMs.

OOM example (taken using gdb)
```
#0  core::sync::atomic::atomic_load () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libcore/sync/atomic.rs:2357
#1  core::sync::atomic::AtomicPtr<T>::load () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libcore/sync/atomic.rs:966
#2  std::alloc::rust_oom () at src/libstd/alloc.rs:278
#3  0x0000555555fbf017 in alloc::alloc::handle_alloc_error () at src/liballoc/alloc.rs:318
#4  0x0000555555a7a306 in alloc::raw_vec::RawVec<T,A>::allocate_in (capacity=1178686224, init=core::alloc::AllocInit::Uninitialized, alloc=...)
    at /home/mb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:185
#5  0x0000555555a7bbf1 in alloc::raw_vec::RawVec<T,A>::with_capacity_in (capacity=1178686224, alloc=...)
    at /home/mb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:159
#6  0x0000555555a798df in alloc::raw_vec::RawVec<T>::with_capacity (capacity=1178686224)
    at /home/mb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:90
#7  0x0000555555a724cf in alloc::vec::Vec<T>::with_capacity (capacity=1178686224)
    at /home/mb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:363
#8  0x0000555555a7d360 in difference::lcs::lcs (orig=..., edit=..., split=...) at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/difference-2.0.0/src/lcs.rs:34
#9  0x0000555555a77c6e in difference::Changeset::new (orig=..., edit=..., split=...) at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/difference-2.0.0/src/lib.rs:97
#10 0x0000555555a31509 in insta::runtime::print_snapshot_diff (workspace_root=0x7ffff0006840, new=0x7ffff788ba00, old_snapshot=..., snapshot_file=..., line=...)
    at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-0.16.1/src/runtime.rs:372
#11 0x0000555555a31c01 in insta::runtime::print_snapshot_diff_with_title (workspace_root=0x7ffff0006840, new_snapshot=0x7ffff788ba00, old_snapshot=..., line=105, snapshot_file=...)
    at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-0.16.1/src/runtime.rs:399
#12 0x0000555555a36382 in insta::runtime::assert_snapshot (refval=..., new_snapshot=..., manifest_dir=..., module_path=..., file=..., line=105, expr=...)
    at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-0.16.1/src/runtime.rs:967
#13 0x00005555559241ed in test_codegen::assert_file (path=...) at tests/test_codegen.rs:105
#14 0x0000555555915555 in test_codegen::tests_k8s::test_clap_yaml () at tests/test_codegen.rs:284
#15 0x00005555557cfa5a in test_codegen::tests_k8s::test_clap_yaml::{{closure}} () at tests/test_codegen.rs:283
#16 0x000055555598a44e in core::ops::function::FnOnce::call_once ()
    at /home/mb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
#17 0x00005555559f618c in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
#18 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:318
#19 std::panicking::try::do_call () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:348
#20 std::panicking::try () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:325
#21 std::panic::catch_unwind () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:394
#22 test::run_test_in_process () at src/libtest/lib.rs:541
#23 test::run_test::run_test_inner::{{closure}} () at src/libtest/lib.rs:450
#24 0x00005555559ce106 in std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/sys_common/backtrace.rs:130
#25 0x00005555559d3205 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/thread/mod.rs:475
#26 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:318
#27 std::panicking::try::do_call () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:348
#28 std::panicking::try () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:325
#29 std::panic::catch_unwind () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:394
#30 std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/thread/mod.rs:474
#31 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libcore/ops/function.rs:233
#32 0x0000555555fa5d4a in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
#33 <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
#34 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:87
#35 0x00007ffff7a05609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#36 0x00007ffff7ecc103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 8
#8  0x0000555555a7d360 in difference::lcs::lcs (orig=..., edit=..., split=...) at /home/mb/.cargo/registry/src/github.com-1ecc6299db9ec823/difference-2.0.0/src/lcs.rs:34
34	    let mut idx: Vec<usize> = Vec::with_capacity(N * M);
(gdb) p N
$1 = 34332
(gdb) p M
$2 = 34332
(gdb) 
```

**Comment by mitsuhiko** [comment]
I agree this would be nice. I would accept a PR for this.
